export enum WorkflowNodeType {
  TRIGGER = 'TRIGGER',
  HTTP = 'HTTP',
  WEBHOOK = 'WEBHOOK',
  DATABASE = 'DATABASE',
  SET = 'SET',
  DELAY = 'DELAY',
  NOTIFICATION = 'NOTIFICATION',
  FORM = 'FORM',
}
